-- SCRIPT DE DATOS PARA RIWICERVEZAS DATABASE

-- TABLA ADMIN

INSERT INTO admins (username, password) VALUES ('admin1', '123');

-- TABLA CATEGORIES

INSERT INTO categories (name) VALUES ('ARTESANAL');
INSERT INTO categories (name) VALUES ('INDUSTRIAL');
INSERT INTO categories (name) VALUES ('SIN TACC');
INSERT INTO categories (name) VALUES ('IMPORTADA');
INSERT INTO categories (name) VALUES ('NACIONAL');
INSERT INTO categories (name) VALUES ('SIN ALCOHOL');

-- TABLA SUBCATEGORIES

INSERT INTO subcategories (name, id_category) VALUES ('IPA',1);
INSERT INTO subcategories (name, id_category) VALUES ('HONEY',1);
INSERT INTO subcategories (name, id_category) VALUES ('SCOTTISH',2);
INSERT INTO subcategories (name, id_category) VALUES ('GOLDEN',2);
INSERT INTO subcategories (name, id_category) VALUES ('GOLDEN ALE',3);
INSERT INTO subcategories (name, id_category) VALUES ('INDIA PALE LAGER',3);
INSERT INTO subcategories (name, id_category) VALUES ('PALE LAGER',4);
INSERT INTO subcategories (name, id_category) VALUES ('SCOTCH ALE',4);
INSERT INTO subcategories (name, id_category) VALUES ('AMBER ALE',5);
INSERT INTO subcategories (name, id_category) VALUES ('AMBER LAGER',5);
INSERT INTO subcategories (name, id_category) VALUES ('BLONDE',6);

-- TABLA SIZES

INSERT INTO sizes (value) VALUES ('330ml');
INSERT INTO sizes (value) VALUES ('500ml');
INSERT INTO sizes (value) VALUES ('473ml');
INSERT INTO sizes (value) VALUES ('710ml');
INSERT INTO sizes (value) VALUES ('730ml');
INSERT INTO sizes (value) VALUES ('350ml');

-- TABLA PRODUCTS
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Ipa Mythos','Cerveza de color amarillo, seca, amarga e intensamente lúpulada. Con un perfil de fermentación limpio que le da gran tomabilidad permitiendo que destaquen los aromas y sabores cítricos y resinosos aportados por los lúpulos Cítra y Simcome.',230,'images-1604795265863.jpg',1,1);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Five Summers','Color amarillo dorado muy intenso. Aromas a maltas y lúpulos típicos de las cervezas lager premium. En boca se muestra muy ligera, con un toque de malta al principio seguida de un final amargo con un toque picante.',200,'images-1604795478199.jpg',2,2);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Apple Fox','Una cerveza pura, con un agradable retrogusto ligeramente amargo. Apple Fox es una cerveza rubia, brillante, que no contiene más que cebada, trigo y el lúpulo. Tiene un aroma con notas de granos y frutas, limpio y puro.',180,'images-1604795616416.jpg',3,3);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Black Pew','Cerveza tipo lager con excelente balance entre cuerpo y sabor suave que representa las tradiciones y costumbres nicaragüenses.',250,'images-1604795851000.jpg',1,4;
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Corona Extra','Cerveza lager de sabor y carácter universal, ideal para tomar en cualquier momento del día. De cuidada elaboración y gran calidad, fruto de la selección de sus materias primas. Destaca su cremosa espuma aromatizada por el lúpulo y su refrescante sabor.',160,'images-1604795937785.jpg',2,1);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('China White','Pale Lager. Cerveza rubia refrescante y ligera con aromas de tequila y acompañados de cítricos, consiguiendo una mezcla perfecta. La cerveza China White es la primera del mundo con un toque de Tequila.',185,'images-1604796038362.jpg',3,2);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Peroni Nastro','Cerveza premium, clásica y auténtica, reconocida mundialmente por su alta calidad, el sabor distintivo y su imagen. Es una cerveza que transmite tranquilidad y relajación, invitando a los consumidores a desconectarse de todos los días a través de experiencias agradables.',180,'images-1604748931713.jpg',1,3);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Amstel Light','American Pale Ale. Aroma a pomelo y pino que lleva a un suave sabor cítrico que finaliza con un carácter robusto de malta.',280,'images-1604756154060.jpg',2,4);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Golden Road','Una cerveza liviana, refrescante y con acidez notoria lograda por el agregado de un cultivo láctico. En sabor y aroma explota en frutas tropicales por el agregado generoso de Guayaba, maracuyá y lima.',200,'images-1604756964665.jpg',3,1);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Bia Saigon','Exquisita Cerveza Premium tipo Blonde Ale,  de color dorado claro, perfil muy suave y balanceado con aroma cítrico y sensación de frescura inigualable.',100,'images-1604758166646.jpg',1,2);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Sol','Cerveza clara, de color dorado, con espuma consistente. Exquisito aroma, fresco y afrutado. Liviana, poco amarga, con un sabor suave y refrescante.',90,'images-1604758357923.jpg',2,3);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Lhasa Beer','Cerveza vietnamita. Cocida con cebada y arroz, tiene un color dorado brillante con una espuma cremosa y espesa. A la nariz es muy limpia y cítrica.',265,'images-1604758410879.jpg',3,4);
INSERT INTO products (name, info, price, image, id_size, id_subcategory) VALUES ('Transatlantica Ipa','Ale clara y dorada. Usa la malta inglesa Maris Otter que crea un dulce sabor. Los lúpulos tradicionales le dan a cerveza un aroma floral delicado.',260,'images-1604759306289.jpg',1,1);

-- DUMMY PRODUCTS

-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Cayman', 'Oth disp fx of lower end unsp humer, subs for fx w nonunion', '934.30', 'https://robohash.org/quiaeteveniet.jpg?size=50x50&set=set1', 4, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Savana', 'Other acquired pure red cell aplasias', '992.96', 'https://robohash.org/estnumquamesse.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('ZDX', 'Fall on or from jungle gym', '745.84', 'https://robohash.org/oditetin.jpg?size=50x50&set=set1', 4, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('CX-9', 'Oth fracture of right lesser toe(s), subs for fx w nonunion', '976.68', 'https://robohash.org/consequaturnumquamprovident.jpg?size=50x50&set=set1', 2, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Firefly', 'Car passenger injured in collision w 2/3-whl mv in traf', '520.28', 'https://robohash.org/veniamistesuscipit.jpg?size=50x50&set=set1', 2, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('GTI', 'Insect bite (nonvenomous) of left ear, subsequent encounter', '842.83', 'https://robohash.org/utodititaque.jpg?size=50x50&set=set1', 1, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Murciélago', 'Laceration of peroneal artery', '162.25', 'https://robohash.org/pariaturtemporarerum.jpg?size=50x50&set=set1', 2, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('FX', 'Toxic effect of taipan venom, intentional self-harm, subs', '451.95', 'https://robohash.org/culpanatusreiciendis.jpg?size=50x50&set=set1', 2, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('SLK55 AMG', 'Varicose veins of r low extrem w ulcer oth part of foot', '703.21', 'https://robohash.org/ipsamidaut.jpg?size=50x50&set=set1', 2, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Cooper Clubman', 'Unspecified sprain of left middle finger, initial encounter', '15.40', 'https://robohash.org/repellendusetomnis.jpg?size=50x50&set=set1', 1, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('911', 'Naegleriasis', '287.04', 'https://robohash.org/accusantiumconsequunturet.jpg?size=50x50&set=set1', 1, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Lancer', 'Incarcerated fx of med epicondyl of l humer, 7thK', '341.02', 'https://robohash.org/fugitametofficia.jpg?size=50x50&set=set1', 2, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Navajo', 'Disp fx of distal phalanx of right thumb, init for clos fx', '370.65', 'https://robohash.org/aututautem.jpg?size=50x50&set=set1', 4, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Laser', 'Exposure of other implanted mesh into organ or tissue, init', '392.83', 'https://robohash.org/cumqueilluma.jpg?size=50x50&set=set1', 4, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Expedition EL', 'Laceration with foreign body, right lower leg, init encntr', '307.81', 'https://robohash.org/vitaeetlaborum.jpg?size=50x50&set=set1', 3, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Riviera', 'Other arthropod infestations', '401.51', 'https://robohash.org/voluptatealiasaut.jpg?size=50x50&set=set1', 4, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Accent', 'Lateral subluxation of left patella', '601.71', 'https://robohash.org/sednesciuntinventore.jpg?size=50x50&set=set1', 1, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Camry', 'Lac w/o fb of low back and pelv w/o penet retroperiton, init', '608.75', 'https://robohash.org/doloremqueametvero.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('8 Series', 'Burn of second degree of unspecified knee, initial encounter', '663.72', 'https://robohash.org/dignissimosetfuga.jpg?size=50x50&set=set1', 2, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Camry', 'Laceration of ovary, unspecified', '20.81', 'https://robohash.org/veniamoccaecatiab.jpg?size=50x50&set=set1', 1, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Capri', 'Unsp injury of ulnar artery at forarm lv, right arm, subs', '531.73', 'https://robohash.org/consequaturestullam.jpg?size=50x50&set=set1', 3, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Legacy', 'Weeks of gestation of pregnancy not specified', '488.82', 'https://robohash.org/ututconsequuntur.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Savana 2500', 'Other accident on other rolling-type pedestrian conveyance', '349.66', 'https://robohash.org/eumatqueunde.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('M', 'Carotid sinus syncope', '28.19', 'https://robohash.org/iustosednesciunt.jpg?size=50x50&set=set1', 2, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('H3', 'Sltr-haris Type II physl fx low end unsp femr, 7thG', '112.22', 'https://robohash.org/perferendisautreiciendis.jpg?size=50x50&set=set1', 2, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Eldorado', 'Blister (nonthermal), left ankle, subsequent encounter', '136.94', 'https://robohash.org/teneturlaudantiumadipisci.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('240', 'Laceration without foreign body of unspecified upper arm', '822.06', 'https://robohash.org/estsuscipitut.jpg?size=50x50&set=set1', 1, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('100', 'Oth abnormal findings in specmn from female genital organs', '274.79', 'https://robohash.org/sedfugitlaudantium.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Ram 2500', 'Contusion of unsp ring finger w damage to nail, subs encntr', '965.21', 'https://robohash.org/commodialiquamut.jpg?size=50x50&set=set1', 2, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Mini', 'Poisoning by other narcotics, intentional self-harm', '997.75', 'https://robohash.org/fugiatvelitasperiores.jpg?size=50x50&set=set1', 2, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('911', 'Asphyx due to being trapped in bed linens, undet, subs', '34.53', 'https://robohash.org/cummaioresin.jpg?size=50x50&set=set1', 1, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('E250', 'Stable burst fx unsp lum vertebra, subs for fx w nonunion', '366.61', 'https://robohash.org/sitdelectusest.jpg?size=50x50&set=set1', 4, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Altima', 'Unsp fracture of right femur, subs for clos fx w delay heal', '497.36', 'https://robohash.org/estvoluptatemet.jpg?size=50x50&set=set1', 1, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('CTS', 'Burn of unspecified degree of left wrist', '846.17', 'https://robohash.org/voluptasearumminus.jpg?size=50x50&set=set1', 1, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('626', 'Other fracture of lower end of unspecified tibia', '297.53', 'https://robohash.org/accusantiumfugiatvoluptates.jpg?size=50x50&set=set1', 1, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Electra', 'Path fx, unsp tibia and fibula, subs for fx w delay heal', '32.11', 'https://robohash.org/eosistenon.jpg?size=50x50&set=set1', 3, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('A7', 'Onchocerciasis', '684.98', 'https://robohash.org/enimexcepturia.jpg?size=50x50&set=set1', 1, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Yukon XL 1500', 'Dislocation of septal cartilage of nose, initial encounter', '94.78', 'https://robohash.org/repudiandaeiustoquia.jpg?size=50x50&set=set1', 4, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Lancer Evolution', 'Insect bite (nonvenomous) of vagina and vulva, sequela', '832.73', 'https://robohash.org/enimeaqueet.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('V8', 'Unsp injury of posterior tibial artery, left leg, subs', '675.35', 'https://robohash.org/nisidolorumsed.jpg?size=50x50&set=set1', 2, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Silverado 1500', 'Congenital malformation of spinal cord, unspecified', '772.58', 'https://robohash.org/exercitationemquieum.jpg?size=50x50&set=set1', 4, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Santa Fe', 'Puncture wound w/o foreign body of vocal cord, subs encntr', '722.27', 'https://robohash.org/autvoluptatesaccusamus.jpg?size=50x50&set=set1', 4, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('600', 'Other allergic and dietetic gastroenteritis and colitis', '869.92', 'https://robohash.org/dolorequivoluptatem.jpg?size=50x50&set=set1', 1, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Land Cruiser', 'Oth fracture of unsp lumbar vertebra, init for clos fx', '619.79', 'https://robohash.org/cumrerumtempora.jpg?size=50x50&set=set1', 3, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Corvette', 'Sltr-haris Type I physl fx lower end humer, right arm, sqla', '584.23', 'https://robohash.org/aspernaturautitaque.jpg?size=50x50&set=set1', 2, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('XK Series', 'Unsp physl fx lower end r fibula, subs for fx w delay heal', '655.48', 'https://robohash.org/debitisvoluptasqui.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('S2000', 'Fracture of unsp shoulder girdle, part unsp, init for opn fx', '977.80', 'https://robohash.org/voluptasautofficia.jpg?size=50x50&set=set1', 3, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Ram 1500', 'Insect bite (nonvenomous), unspecified knee', '427.34', 'https://robohash.org/sitnecessitatibusipsam.jpg?size=50x50&set=set1', 1, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Stanza', 'Unsp fracture of unsp forearm, subs for clos fx w malunion', '726.03', 'https://robohash.org/etofficiaharum.jpg?size=50x50&set=set1', 3, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Forenza', 'Unspecified open wound of right hand', '719.22', 'https://robohash.org/ipsumsapienteminima.jpg?size=50x50&set=set1', 3, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Legacy', 'Nondisplaced segmental fracture of shaft of ulna, unsp arm', '232.83', 'https://robohash.org/fugiatquisquamoccaecati.jpg?size=50x50&set=set1', 1, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Grand Marquis', 'Injury of digital nerve of right little finger, sequela', '39.47', 'https://robohash.org/facilisetet.jpg?size=50x50&set=set1', 4, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Viper', 'Burn first deg mult sites of shldr/up lmb, ex wrs/hnd, init', '130.54', 'https://robohash.org/placeatetqui.jpg?size=50x50&set=set1', 4, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Mazda6 Sport', 'Nondisp commnt fx shaft of unsp femr, 7thN', '178.83', 'https://robohash.org/similiquesequiquae.jpg?size=50x50&set=set1', 2, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Sable', 'Separation of muscle (nontraumatic), thigh', '357.86', 'https://robohash.org/nequequiarchitecto.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('3 Series', 'Nondisp fx of distal phalanx of right little finger, sequela', '138.48', 'https://robohash.org/eumlaboreex.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Catera', 'Terrorism involving nuclear weapons, terrorist injured, init', '625.48', 'https://robohash.org/etatqueasperiores.jpg?size=50x50&set=set1', 1, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Suburban 1500', 'Rheumatoid bursitis, unspecified site', '566.14', 'https://robohash.org/excepturisaepenihil.jpg?size=50x50&set=set1', 4, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Voyager', 'Blister (nonthermal), right lower leg, sequela', '888.49', 'https://robohash.org/nostrumquaeea.jpg?size=50x50&set=set1', 2, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Aurora', 'Chronic gout due to renal impairment, right elbow, w/o toph', '56.55', 'https://robohash.org/quiasapienteautem.jpg?size=50x50&set=set1', 1, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Z3', 'Injury of cutaneous sensory nerve at lower leg level', '240.47', 'https://robohash.org/teneturconsequaturvoluptate.jpg?size=50x50&set=set1', 3, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Dynasty', 'Strain intrns musc/fasc/tend l lit fngr at wrs/hnd lv, subs', '107.83', 'https://robohash.org/extemporecumque.jpg?size=50x50&set=set1', 2, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Firefly', 'Encephalitis and encephalomyelitis, unspecified', '272.82', 'https://robohash.org/maioressuscipiteos.jpg?size=50x50&set=set1', 1, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Express 1500', 'Corrosion of first degree of left toe(s) (nail)', '698.33', 'https://robohash.org/itaquequibusdamamet.jpg?size=50x50&set=set1', 1, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Protege5', 'Benign neoplasm of left ciliary body', '652.27', 'https://robohash.org/exaperiampossimus.jpg?size=50x50&set=set1', 1, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Justy', 'Drug-induced gout, hip', '734.14', 'https://robohash.org/voluptatemnesciuntmollitia.jpg?size=50x50&set=set1', 4, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('6 Series', 'Contusion of unsp lesser toe(s) w/o damage to nail, subs', '340.33', 'https://robohash.org/impeditquieum.jpg?size=50x50&set=set1', 1, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Mark LT', 'Type 1 diabetes mellitus with hyperglycemia', '577.88', 'https://robohash.org/commodirepellatveritatis.jpg?size=50x50&set=set1', 3, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Town & Country', 'Episodic cluster headache, intractable', '712.17', 'https://robohash.org/providentnonlaudantium.jpg?size=50x50&set=set1', 2, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Regal', 'Spondylolisthesis, thoracic region', '962.45', 'https://robohash.org/velitvelitofficia.jpg?size=50x50&set=set1', 1, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('3500', 'Nondisp fx of prox phalanx of l mid fngr, 7thK', '265.17', 'https://robohash.org/minimadictaquod.jpg?size=50x50&set=set1', 3, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Z4', 'Enteropathic arthropathies, knee', '148.31', 'https://robohash.org/laborummagniet.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Phaeton', 'Placenta accreta, second trimester', '710.13', 'https://robohash.org/etexplicabodolor.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('XJ Series', 'Oth fx shaft of left femur, subs for clos fx w nonunion', '928.23', 'https://robohash.org/etdistinctioaut.jpg?size=50x50&set=set1', 1, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Avalon', 'Miscellaneous anesthesiology devices assoc w incdt, NEC', '867.56', 'https://robohash.org/voluptasevenietex.jpg?size=50x50&set=set1', 3, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('LTD Crown Victoria', 'Passenger of snowmobile injured in nontraffic accident', '98.39', 'https://robohash.org/eumdistinctioenim.jpg?size=50x50&set=set1', 3, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('SLK-Class', 'Dissection of other specified artery', '737.01', 'https://robohash.org/sapienteinventoremagni.jpg?size=50x50&set=set1', 2, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Grand Am', 'Nondisp trimalleol fx r low leg, subs for clos fx w malunion', '211.33', 'https://robohash.org/similiqueearumsit.jpg?size=50x50&set=set1', 4, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('XC90', 'Age-related osteopor w current path fracture, shoulder', '675.07', 'https://robohash.org/eosanimiplaceat.jpg?size=50x50&set=set1', 2, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Outlook', 'Pressure ulcer of head', '981.32', 'https://robohash.org/autemnullavero.jpg?size=50x50&set=set1', 1, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Odyssey', 'Major osseous defect, left pelvic region and thigh', '186.66', 'https://robohash.org/providentsintsed.jpg?size=50x50&set=set1', 4, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('RL', 'Personal history of malig neoplasm of urinary tract organ', '847.66', 'https://robohash.org/esteumid.jpg?size=50x50&set=set1', 4, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('XJ Series', 'Occup of bus injured in collision w ped/anml in traf', '125.81', 'https://robohash.org/voluptatemtotamautem.jpg?size=50x50&set=set1', 4, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Corvette', 'Underdosing of unsp hormones and synthetic substitutes, init', '970.36', 'https://robohash.org/oditinlabore.jpg?size=50x50&set=set1', 4, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('M6', 'Poisoning by methylphenidate, intentional self-harm, init', '153.03', 'https://robohash.org/consequunturdeseruntreiciendis.jpg?size=50x50&set=set1', 3, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('1500', 'Opn wnd abdomen, lower back, pelvis and external genitals', '446.36', 'https://robohash.org/architectoomniseos.jpg?size=50x50&set=set1', 4, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Focus', 'Complete traum amp at level betw knee and ankl, unsp low leg', '253.23', 'https://robohash.org/estestconsequatur.jpg?size=50x50&set=set1', 3, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Pathfinder', 'Salpingitis and oophoritis, unspecified', '84.51', 'https://robohash.org/omnisquivoluptatem.jpg?size=50x50&set=set1', 4, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('X-90', 'Amebic nondysenteric colitis', '878.81', 'https://robohash.org/veroineaque.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Town & Country', 'Lac w/o fb of right lesser toe(s) w damage to nail, sequela', '910.52', 'https://robohash.org/quomaioresqui.jpg?size=50x50&set=set1', 4, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Aspire', 'Complete lesion at T11-T12, init', '33.27', 'https://robohash.org/laboriosamillumvero.jpg?size=50x50&set=set1', 2, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Club Wagon', 'Corros unsp deg mult sites of head, face, and neck, init', '886.71', 'https://robohash.org/nesciuntvoluptatemconsequatur.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('R-Class', 'Contus/lac l cereb w LOC w dth d/t brain inj bf consc, sqla', '11.63', 'https://robohash.org/odiomagnamreiciendis.jpg?size=50x50&set=set1', 3, 1);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Sierra 1500', 'Neoplasm of uncertain behavior of meninges, unspecified', '582.68', 'https://robohash.org/istenonest.jpg?size=50x50&set=set1', 1, 5);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Ram 2500', 'Erythromelalgia', '383.58', 'https://robohash.org/quilaudantiumnumquam.jpg?size=50x50&set=set1', 4, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Rainier', 'Contusion of right little finger w damage to nail, init', '168.45', 'https://robohash.org/etdictasunt.jpg?size=50x50&set=set1', 4, 3);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Aerostar', 'Other injury of celiac artery, sequela', '122.66', 'https://robohash.org/nonveltempora.jpg?size=50x50&set=set1', 4, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Liberty', 'Burn of unsp degree of unsp scapular region, init encntr', '71.44', 'https://robohash.org/ipsamvelalias.jpg?size=50x50&set=set1', 1, 2);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Bronco II', 'Superficial (capsular) laceration of spleen, subs encntr', '753.71', 'https://robohash.org/quaseosmaxime.jpg?size=50x50&set=set1', 4, 4);
-- insert into products (name, info, price, image, id_size, id_subcategory) values ('Elan', 'Type 2 diabetes mellitus with diabetic amyotrophy', '962.26', 'https://robohash.org/essesolutasuscipit.jpg?size=50x50&set=set1', 2, 1);



-- TABLA USERS

INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Guillermo','Katz','gkatz@dh.com','1988-03-15','Bolivar 7001','$2b$10$4anIA3Do.ReboZrnl0fQ1e0zDmcbYLmqkGGIxIs8e252URNUaBoNG');
INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Santiago','Cura','scura@dh.com','1988-11-21','Piedras 222','$2b$10$AUcUzdCGn6kNBQb5.1H0ZuZ.gEkAp0L7eev3m6ouvP5QlTgmjwbDC');
INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Carlos','Maldonado','pachi@dh.com','1977-02-01','Avenida Los Pinos 333','$2b$10$d.KmykXNxjwjENIbXIm51uZuHvD4KF6TsO5r1wS1I3BnSkZqevzQu');

-- DUMMY USERS

-- INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Ana','Lopez','analo@dh','1980-04-07','Villa Yrigoyen M4 C3','$2b$10$V78QmA7Yf2l2aruzRCGSJOBmfor7rs/WiIArL2IItbQOr/p4yX9rW');
-- INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Pedro','Juarez','pedrojua@dh.com','2000-10-30','Av Gral Paz 3605','$2b$10$Dkk0LSL5gTFk.mDiipIaperbaEZAVyOgDiGtkGtQ9bTy3gFBjaM1.');
-- INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Sandra','Centeno','sancen@dh','2000-05-05','Av Roca 1001','$2b$10$d/KIJkcb4Ilr/6dQQKTYh.bXofPvw4EQflHGpPGO5dcUHnueWHGdG');
-- INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Rodrigo','Hache','rodrihach@dh','1990-07-08','Piedras 1124','$2b$10$xHn0QirBye2UCd8fn69q2esMi2544vPOU8SYAafjMJX6WEs0U7Puq');
-- INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Carla','Gutierrez','caralgu@ho','1980-10-10','Rondeau 2044','$2b$10$Rh8OFs2bHDEwJ25dvYiuweiEFAp7sqd1M4ku5k8.Kc11i6c7FJDuy');
-- INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Adolfo','Sosa','adososa@dh','1977-04-02','Bolivar 455','$2b$10$Pnt44YeC1Mni8i75IpQSfutq8aO1jFEjUZqjfJ.wHWXNL/AF.RL9K');
-- INSERT INTO users (first_name, last_name, email, birthdate, address, password) VALUES ('Nicky','Keith','nkeith0@cam.ac.uk','1972-08-02','76 Del Mar Drive','$2b$10$b8k/SXVCQ.382DnLcz6Ivuhm3fAHvVpMJTTf.NHbg46NX6Pwkw9ZO');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Dominique', 'Workes', 'dworkes0@godaddy.com', '1999/01/07', '61 Annamark Pass', 'UHqqH4t4U0z');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Audra', 'Ings', 'aings1@bing.com', '1982/08/03', '9 Eastlawn Lane', 'JoRuHa');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Robbie', 'Bento', 'rbento2@wikipedia.org', '2003/04/04', '6 Melby Terrace', 'M9i9DDlMm4i');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Thacher', 'Philp', 'tphilp3@liveinternet.ru', '1981/10/15', '9 Del Sol Pass', 'cPvjKd92n');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Dugald', 'Dufore', 'ddufore4@yellowpages.com', '2003/02/02', '9 Glendale Way', 'CRkM00LlJb');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Wye', 'Bottrill', 'wbottrill5@addtoany.com', '2002/10/03', '15 Green Park', 'WuGsQvKuA8');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Alanson', 'Ilsley', 'ailsley6@cbc.ca', '1991/05/10', '0978 Macpherson Pass', 'ZKumaXkk');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Elinore', 'Truran', 'etruran7@comcast.net', '1984/04/27', '59 Portage Parkway', 'ZEaj2xa7');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Sergio', 'De Bell', 'sdebell8@yandex.ru', '2010/02/24', '5493 Vera Parkway', 'E7Vc5u');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Lynde', 'Sponder', 'lsponder9@goodreads.com', '1987/08/15', '25 Brentwood Court', 'WfQM9a3QwGe');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Julianne', 'Enright', 'jenrighta@time.com', '1972/04/28', '682 Trailsway Street', 'I7LhZ17kBIyR');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Shaine', 'Guinness', 'sguinnessb@nymag.com', '2006/02/13', '734 Green Ridge Point', '6UWdASTZwK');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Sharyl', 'Blackler', 'sblacklerc@apple.com', '1997/01/23', '376 Bayside Parkway', '4BMZ7pR');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Boyce', 'Geffcock', 'bgeffcockd@shinystat.com', '1996/05/30', '9 Forest Run Point', 'TJKK3nb85OV');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Gary', 'Vinnicombe', 'gvinnicombee@paginegialle.it', '1986/06/06', '0 Columbus Point', 'EClQygBlx0YD');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Angel', 'Sproule', 'asproulef@gravatar.com', '1981/08/12', '044 Forest Road', 'htl7uStL');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Olga', 'Jeste', 'ojesteg@disqus.com', '2006/12/03', '26 Kropf Trail', 'UbX5jVOuSZCt');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Iormina', 'Antal', 'iantalh@java.com', '1990/09/17', '310 Merry Road', 'odt037qhlvIG');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Dolf', 'Lawtie', 'dlawtiei@gmpg.org', '2009/07/22', '0 Brown Place', 'FZNV6l4M4UDy');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Cesare', 'Meysham', 'cmeyshamj@auda.org.au', '1976/11/04', '526 Autumn Leaf Street', 'xuAWwHgQ2A');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Jamison', 'Matveichev', 'jmatveichevk@nature.com', '1993/05/04', '892 Hermina Way', 'UOC4Vbp6Q1H9');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Eleanora', 'Clayal', 'eclayall@mashable.com', '1973/09/09', '306 Arizona Park', '0Hr7uGG0tz');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Adair', 'Reinhart', 'areinhartm@zimbio.com', '1974/04/03', '00526 Calypso Crossing', '5LCoK04');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Bertrando', 'Walcot', 'bwalcotn@infoseek.co.jp', '1978/04/13', '36 Sutherland Way', 'egYLt2j1g8');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Margette', 'Gullifant', 'mgullifanto@last.fm', '2003/09/17', '75 Mccormick Drive', 'LM81eBE');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Anette', 'Gumb', 'agumbp@cisco.com', '1998/06/06', '3 Hoffman Road', '59UZm8RqGGZF');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Quintilla', 'Howis', 'qhowisq@cpanel.net', '1987/10/11', '081 Butterfield Parkway', 'nzSN5wexcHi');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Linzy', 'Brislan', 'lbrislanr@smh.com.au', '1999/12/27', '893 Village Green Road', 'kCLwdHk');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Herbert', 'de Clerq', 'hdeclerqs@google.co.uk', '2004/11/30', '34634 2nd Place', '6MVrThPudRYZ');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Vivia', 'Adkins', 'vadkinst@google.pl', '1985/02/11', '843 High Crossing Hill', 'tBHaYgFe5L');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Sancho', 'Goad', 'sgoadu@pen.io', '1982/12/02', '99675 Holmberg Pass', 'XGAyJkVMdWq');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Haslett', 'De Blasio', 'hdeblasiov@ca.gov', '1989/11/12', '1961 Hayes Crossing', 'Qye6lIm');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Dougy', 'Blanch', 'dblanchw@eepurl.com', '1972/03/04', '753 Memorial Terrace', '5fTRD6HsuPi');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Phaidra', 'Craiker', 'pcraikerx@comcast.net', '1975/02/16', '11 Commercial Street', '24K6uRn');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Wally', 'Ebhardt', 'webhardty@wsj.com', '1984/07/22', '9 Sachs Point', 'tkE5sVGOOMN');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Phip', 'Moulsdall', 'pmoulsdallz@vinaora.com', '2004/11/22', '92 Schiller Street', 'kVqLRR7');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Dara', 'Sutherley', 'dsutherley10@livejournal.com', '1989/10/15', '7 Norway Maple Road', '342C6Y1kKr');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Danielle', 'Sirette', 'dsirette11@google.it', '1974/10/19', '48247 Derek Trail', 'FzXTBKObQ');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Erskine', 'MacSween', 'emacsween12@wisc.edu', '2005/06/19', '11776 Donald Drive', 'dsTpB4');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Willie', 'Rowling', 'wrowling13@state.tx.us', '1988/03/28', '590 Donald Street', 'gftpCPku7K');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Geneva', 'Starford', 'gstarford14@biblegateway.com', '1998/05/23', '7575 Golf Course Avenue', 'PKbHUZsUy');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Joice', 'Girardet', 'jgirardet15@answers.com', '1977/09/20', '93 Sommers Junction', 'J5gCdMxOjfnT');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Bonny', 'Muffin', 'bmuffin16@netlog.com', '1981/10/19', '5546 Miller Parkway', 'CySHS6qE');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Reeva', 'Huelin', 'rhuelin17@ycombinator.com', '2007/11/13', '59 Delaware Court', 'DIflsG');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Mirelle', 'Ellis', 'mellis18@cnet.com', '2000/04/03', '02628 4th Street', 'x8eWn0Wj');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Gaylene', 'Abbado', 'gabbado19@hhs.gov', '1994/06/26', '9 Morningstar Lane', '7dFj7a');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Kyrstin', 'O''Hara', 'kohara1a@unblog.fr', '2000/06/21', '68 Coolidge Circle', 'mv8MXw7mhI');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Hanny', 'Matschuk', 'hmatschuk1b@redcross.org', '1973/09/30', '82 Bluestem Trail', 'XHNprB3LJr');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Karen', 'Doughill', 'kdoughill1c@baidu.com', '1971/07/14', '35016 7th Circle', 'bvxSaa68yGb');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Leeland', 'Liddiatt', 'lliddiatt1d@icio.us', '1975/11/09', '19 Golden Leaf Lane', 'of0SJvR5LRPt');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Roberta', 'Greengrass', 'rgreengrass1e@gov.uk', '1985/05/08', '94 Emmet Parkway', 'YLuy8E');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Jolynn', 'Epple', 'jepple1f@constantcontact.com', '2010/03/08', '70 Buell Avenue', 'cOE2kf');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Ilaire', 'Fleetham', 'ifleetham1g@bloglovin.com', '1992/12/13', '78 Pine View Court', '3n7Pyha');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Austina', 'Smewing', 'asmewing1h@nih.gov', '1999/02/15', '1 Warbler Drive', 'KcOaXzgUdr');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Pieter', 'Stit', 'pstit1i@cnet.com', '1972/06/05', '235 Eastlawn Point', 'td8y1gViZ');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Frazer', 'Edmenson', 'fedmenson1j@seesaa.net', '1977/04/04', '72026 Dixon Pass', 'TuNNbz6O');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Carmel', 'Tremmil', 'ctremmil1k@twitpic.com', '1983/08/30', '33 Hanson Point', 'nmEv4HD8J');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Ado', 'Tomaszczyk', 'atomaszczyk1l@state.gov', '1999/01/01', '2502 High Crossing Lane', 'CAayNMHMOHU');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Gil', 'Keme', 'gkeme1m@si.edu', '1982/07/29', '819 School Park', 'oicHUixvk');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Delphine', 'Warret', 'dwarret1n@tripod.com', '1986/02/12', '14 Iowa Street', 'FdmFNR');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Tim', 'Rainbow', 'trainbow1o@facebook.com', '1978/10/23', '632 Northport Lane', '6ZhJQIREmgyv');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Elysha', 'Gansbuhler', 'egansbuhler1p@kickstarter.com', '1991/12/26', '8648 Dottie Street', 'b1MwSRb');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Linn', 'Giannini', 'lgiannini1q@flavors.me', '1982/10/04', '26 Homewood Hill', 'L9WpPjJk4w4');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Florette', 'Sharrier', 'fsharrier1r@t-online.de', '1975/07/18', '12377 Oneill Terrace', '24EozC0c');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Christie', 'Gedge', 'cgedge1s@ycombinator.com', '1985/07/24', '02916 Elgar Circle', 'Yn81NTL');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Florance', 'Krammer', 'fkrammer1t@amazon.co.uk', '1995/07/23', '16 Armistice Pass', 'mlbjaBtw');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Vally', 'Coulter', 'vcoulter1u@prlog.org', '1984/02/10', '32 Everett Pass', '5KQwnEJPFlC8');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Phillie', 'Vampouille', 'pvampouille1v@yahoo.co.jp', '1984/10/06', '35 Florence Hill', 'mhQQh1s8P3gj');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Carlynne', 'Panons', 'cpanons1w@acquirethisname.com', '1991/05/02', '9 Lawn Park', 'Bmuhh25uAL1');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Borden', 'McDade', 'bmcdade1x@flavors.me', '1983/05/02', '025 Hallows Street', '3brpvmTUWVOu');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Calvin', 'Antunes', 'cantunes1y@nifty.com', '2009/05/26', '4 Warner Hill', 'hTzjybpVOG');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Wynne', 'Lacase', 'wlacase1z@sourceforge.net', '1999/10/17', '9364 Marcy Alley', 'fnfuoZCGR');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Ambrosi', 'Carden', 'acarden20@hc360.com', '2008/04/24', '20806 Hoepker Parkway', 'w1UJPRnvI');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Loralee', 'Roony', 'lroony21@vk.com', '1979/11/13', '17 Mitchell Crossing', 'NlnrCufff');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Hermine', 'Jedraszek', 'hjedraszek22@elegantthemes.com', '2003/11/02', '923 Shelley Junction', '1XAutnQK');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Nicky', 'Outram', 'noutram23@qq.com', '1974/10/11', '52 Hansons Point', 'fxOUACC');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Rees', 'Dulwitch', 'rdulwitch24@privacy.gov.au', '1980/05/19', '2430 Morning Road', 'NmXMvIdW');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Annalee', 'Ransfield', 'aransfield25@oracle.com', '1996/10/28', '7 Boyd Place', 'JLO6kwc54x');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Faythe', 'Elington', 'felington26@theglobeandmail.com', '1994/02/22', '570 Dryden Court', 'IjCL7sK7ld');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Goddart', 'Ault', 'gault27@scribd.com', '1996/05/11', '4460 Scoville Street', 'ffH9hQ');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Malachi', 'Mulvihill', 'mmulvihill28@cocolog-nifty.com', '1999/08/23', '59116 Bultman Court', 'nLY0EQ8');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Reine', 'Walbridge', 'rwalbridge29@mit.edu', '2010/07/08', '217 Hovde Avenue', 'ATSBcuY');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Iolande', 'De Haven', 'idehaven2a@virginia.edu', '1975/01/20', '20243 Armistice Point', 'PpXFsGfUM3P');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Siegfried', 'Rawdales', 'srawdales2b@w3.org', '2001/07/17', '9339 Lakewood Way', '5PIj8matB');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Teresa', 'MacAskie', 'tmacaskie2c@earthlink.net', '2007/02/04', '38 Northport Junction', 'eANtyUE2');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Sergei', 'Dowley', 'sdowley2d@uiuc.edu', '2004/09/21', '613 Oakridge Plaza', 'hSLnBhJMvH');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Austen', 'Cusworth', 'acusworth2e@cargocollective.com', '1997/05/20', '09 Spaight Avenue', 'jzoIsMTOPuT');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Maddie', 'Hawley', 'mhawley2f@usgs.gov', '1972/09/05', '701 Sugar Junction', 'n6b9q3');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Layton', 'Algie', 'lalgie2g@friendfeed.com', '1998/02/10', '10 Fremont Pass', 'hrhtF8u25');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Zena', 'Fishburn', 'zfishburn2h@mozilla.org', '1976/05/04', '5178 Mccormick Street', 'b7JHWB2');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Lilly', 'Rillatt', 'lrillatt2i@hatena.ne.jp', '1997/02/27', '7806 Union Place', 'mKfiSJx');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Idelle', 'Tull', 'itull2j@kickstarter.com', '1979/06/08', '20095 Carpenter Court', 'cqaOnH2X');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Rois', 'Djurevic', 'rdjurevic2k@hp.com', '1979/06/13', '5 Transport Place', 'vC748aZDPhjI');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Carin', 'Inglese', 'cinglese2l@google.com.au', '2007/08/11', '24954 4th Crossing', 'ipq3gTt');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Heather', 'Faulds', 'hfaulds2m@bigcartel.com', '2008/10/15', '99997 Summit Plaza', 'mMGR75S');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Carlotta', 'Digges', 'cdigges2n@wsj.com', '1989/06/21', '535 Morningstar Place', '3yocCQpq');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Emiline', 'Figliovanni', 'efigliovanni2o@cnn.com', '1973/11/23', '83643 Caliangt Road', 'gs8ulsu');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Ilka', 'Keppy', 'ikeppy2p@tripadvisor.com', '1980/05/05', '28350 Dawn Street', 'SBJae1CUtqD');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Kin', 'Abden', 'kabden2q@newsvine.com', '1971/12/20', '710 Lake View Way', 'jnWMoCw');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Falito', 'Tabb', 'ftabb2r@fda.gov', '1978/04/27', '60473 West Road', 'dfzpN6H2tN');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Carlene', 'Few', 'cfew2s@surveymonkey.com', '1998/10/28', '552 Tennyson Alley', 'nEo5ToIyy0vH');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Ernest', 'Goldman', 'egoldman2t@alibaba.com', '1992/01/27', '35 Independence Avenue', '1kB1aNPhqVJ');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Jacquenette', 'Whitnell', 'jwhitnell2u@wired.com', '2002/05/09', '84088 Vera Plaza', 'S9sjMZqN');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Tabbitha', 'Malpas', 'tmalpas2v@forbes.com', '1976/03/28', '08 Truax Hill', 's8sVipwzs7Y');
-- insert into users (first_name, last_name, email, birthdate, address, password) values ('Beale', 'Coppard', 'bcoppard2w@ebay.co.uk', '1979/09/17', '35 Mallory Parkway', '99QUGc');
